org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# KILL SPACE-IN-PATH ERROR (Using Short Path to Reuse Cache)
org.gradle.project.android.home=C\:\\Users\\NITINK~1\\.android
org.gradle.user.home=C\:\\Users\\NITINK~1\\.gradle
